Feat: breadcrumbs in settings
medusajs/admin pull request #113
Opened 2021-09-29 08:08 UTC by pKorsholm

**What**
- Add breadcrumbs to settings

**How**
- Add breadcrumb component

**Why**
- improve understanding of current page and context

**Testing** 
- manual testing

2021-09-30 06:24 UTC, olivermrbl requested changes

2021-09-30 06:24 UTC, olivermrbl commented on src/domain/settings/return-reasons/edit.js
> +        />
Missing import

2021-09-30 06:49 UTC, pKorsholm commented on src/domain/settings/return-reasons/edit.js
> +        />
Added it 😄

2021-10-01 08:27 UTC, olivermrbl approved these changes

2021-10-01 09:20 UTC, merged