Feat/revamp sidebar
medusajs/admin pull request #203
Opened 2021-12-22 08:39 UTC by pKorsholm

**What**
- design update to the sidebar in admin according to the revamp design in figma

**How**
- Introduced new molecules: 
  - Sidebar-company-logo
  - Sidebar-menu-item
  - Sidebar-team-member
- introduced new organisms: 
  - Sidebar-team
  - Invite-modal
- create folders for icons in admin under `src/assets/svg/2.0/<Size (16px/20px/24px)>/<name>`

**Note** 
- the `your team` part of the admin bar is still being developed (currently only missing overflow behavior which I'm talking to Ludvig about), and will be cleaned up and mock data will be removed before being merged, but it's there as a demonstration for now

2021-12-28 13:24 UTC, olivermrbl requested changes
Let's change the icons to components and add them to fundamentals. See existing icons on branch `feat/revamp` for reference.

In the case of non-existing names on users, the emails in the sidebar are quite long. Could we add an ellipsis or similar? We might need to rethink the design a bit. Have attached an image showing the issue:
![image](https://user-images.githubusercontent.com/59018053/147570664-b7a421b6-4546-4b06-abfe-cfa4e59e0b52.png)

2021-12-29 10:56 UTC, olivermrbl requested changes
In regards to the note in the PR description, how far are we on this? Would be great to get it cleaned up asap :)

2021-12-29 10:56 UTC, olivermrbl commented on src/components/molecules/sidebar-company-logo/index.js
> +    <div className='flex px-2 mt-12 mb-3.5 items-center'>
Remove margin-top from company logo. The general layout will take care of the positioning

2022-01-04 07:50 UTC, pKorsholm commented
I have updated the PR with the following: 
- remove `assets/svg/2.0` folder entirely in favor of the different approach in `feat/revamp` 
- add icons to `fundamentals` as `.tsx` files
- fix missing overflow issue in the team sidebar
- merge the new sidebar with the layout from `feat/revamp` removing the old sidebar and fixing the styling 
- convert all files related to the sidebar to `.tsx`

wrgt the note in the pr its still listed as `coming soon` in radix, I think we should merge this if it is deemed to work, and implement the carousel later when it gets released from radix :smile:

2022-01-04 13:12 UTC, olivermrbl requested changes
Really great. Some required changes here and there primarily related to the fact that we now use types from TS for components :)

2022-01-04 13:12 UTC, olivermrbl commented on src/components/molecules/sidebar-company-logo/index.tsx
> +}
Should use type instead

2022-01-04 13:12 UTC, olivermrbl commented on src/components/molecules/modal/index.js
> +}
Now that we've decided to add TS, let's change the component to `.tsx` and use types instead of PropTypes

2022-01-04 13:12 UTC, olivermrbl commented on src/components/molecules/sidebar-menu-item/index.tsx
> +}
Should be converted to a type and have it's prefixed "I" removed

2022-01-04 13:12 UTC, olivermrbl commented on src/components/molecules/sidebar-team-member/index.tsx
> +}
Same as above

2022-01-04 13:12 UTC, olivermrbl commented on src/components/organisms/sidebar.tsx
> +      console.log(data)
rm

2022-01-04 13:12 UTC, olivermrbl commented on src/components/organisms/sidebar-team/index.tsx
> +  ]
Remove

2022-01-04 13:14 UTC, olivermrbl commented on src/components/organisms/sidebar-team/index.tsx
> +  ]
As well as the usage when rendering users :)

2022-01-06 15:09 UTC, olivermrbl requested changes
Great work! Just a couple of tiny changes here and there 👍

2022-01-06 15:09 UTC, olivermrbl commented on src/components/fundamentals/button/index.tsx
> +    console.log(classes)
rm

2022-01-06 15:09 UTC, olivermrbl commented on src/components/fundamentals/button/index.tsx
> +    const classes = clsx(buttonClass, attributes.className)
Is this necessary?

2022-01-06 15:09 UTC, olivermrbl commented on src/components/molecules/modal/index.tsx
> +  console.log(largeModal)
rm

2022-01-06 15:09 UTC, olivermrbl commented on src/components/molecules/modal/index.tsx
> +  console.log(largeModal)
rm

2022-01-06 15:09 UTC, olivermrbl commented on src/components/sidebar/old-index.js
> +import React, { useEffect, useState } from "react"
Are we still using the old sidebar?

2022-01-07 10:46 UTC, olivermrbl approved these changes
LGTM, great work !! 🤟

2022-01-07 11:21 UTC, merged