feat: revamp two split body
medusajs/admin pull request #221
Opened 2022-01-05 16:30 UTC by kasperkristensen

**What**
- Adds two split view

**How**
To use the component you will add a `<TwoSplitPane></TwoSplitPane>` which can hold two `BodyCard` components as children. If you add more then two children the component will throw an error.

**Responsiveness**
I've added some very rudimental responsiveness to the component, but I definitely think we should revisit this once Ludvig has taken a look at how this component should look on different screen sizes. 

**Note**
PR `feat/revamp-buttons` and `fix/icon-type` should be merged beforehand

<img width="1201" alt="Skærmbillede 2022-01-05 kl  17 23 32" src="https://user-images.githubusercontent.com/45367945/148252602-a9f844eb-efd1-451d-be6e-f7722b4535d4.png">

2022-01-09 15:25 UTC, olivermrbl requested changes
Great work Kasper! Minor changes required 👍

2022-01-09 15:25 UTC, olivermrbl commented on src/components/molecules/actionables.tsx
> +  if (actions.length === 0) {
Should check if actions is `undefined`, since they are not required
```suggestion
  if (actions?.length === 0) {
```

2022-01-09 15:25 UTC, olivermrbl commented on src/components/molecules/actionables.tsx
> +  actions: ActionType[]
Should be optional right?

2022-01-09 15:25 UTC, olivermrbl commented on src/components/organisms/body-card.tsx
> +    <div className="rounded-rounded border bg-grey-0 border-grey-20 h-full overflow-hidden flex flex-col min-h-[500px] w-full medium:w-1/2 relative">
Should have a smaller min-height. See currency settings [here](https://www.figma.com/file/dlraOnQvQnrHQL0A7Ysbrs/Webapp-2.0?node-id=74%3A87).

2022-01-09 15:25 UTC, olivermrbl commented on src/components/organisms/body-card.tsx
> +    <div className="rounded-rounded border bg-grey-0 border-grey-20 h-full overflow-hidden flex flex-col min-h-[500px] w-full medium:w-1/2 relative">
Suggestion would be `400px`

2022-01-10 16:54 UTC, pKorsholm commented
Should the `BodyCard` be able to be used without putting it in a `TwoSplitPane`?

If you try that now it's still half split, I would suggest we make it full width and have the `TwoSplitPane` adjust the width of the `BodyCard`. Then in sub menus with only one side we would still use the `TwoSplitPane` and have the same halving effect, but we can use the `BodyCard` for full width components.

I.e remove `medium:w-1/2` from the outer `div` of `BodyCard` and adjust the `TwoSplitPane` to map children like so: 

```javascript
{Children.map(children, (child, i) => {
  return (
    <div className="medium:w-1/2" key={i}>
      {child}
    </div>
  )
})}
```

2022-01-11 09:06 UTC, kasperkristensen commented
> Should the `BodyCard` be able to be used without putting it in a `TwoSplitPane`?
> 
> If you try that now it's still half split, I would suggest we make it full width and have the `TwoSplitPane` adjust the width of the `BodyCard`. Then in sub menus with only one side we would still use the `TwoSplitPane` and have the same halving effect, but we can use the `BodyCard` for full width components.
> 
> I.e remove `medium:w-1/2` from the outer `div` of `BodyCard` and adjust the `TwoSplitPane` to map children like so:
> 
> ```js
> {Children.map(children, (child, i) => {
>   return (
>     <div className="medium:w-1/2" key={i}>
>       {child}
>     </div>
>   )
> })}
> ```

Totally agree! I've added it to the update 👍

2022-01-11 11:40 UTC, olivermrbl approved these changes
LGTM!

2022-01-11 14:44 UTC, merged