Feat: Revamp filter dropdown
medusajs/admin pull request #263
Opened 2022-01-24 16:52 UTC by pKorsholm

**What** 
- revamp of filter dropdown
- revamp of filter dropdown items
- revamp of filter dropdown date pickers

**How**
- The trigger is passed as a parameter to the container
- The children of the container is shown in the list

![image](https://user-images.githubusercontent.com/88927411/150826929-63170a3c-7b05-4ed7-aff9-db635ac1861e.png)

![image](https://user-images.githubusercontent.com/88927411/150827018-74f90a32-7a2b-4073-9d35-9e0a9de65530.png)

dependent on #257

2022-01-25 16:00 UTC, kasperkristensen requested changes
Looks very good! Not sure if it is due to the the new filter menu being used together with the old one, but I am seeing some strange behaviour fx when I choose to filter by date then it first show a date picker above the menu, and after I select a date a new date picker pops up on the left side of the screen. And the second date picker is only able to be cancelled.

![image](https://user-images.githubusercontent.com/45367945/151011662-58cd8a7b-c5b5-40a2-a129-73cdb469c02d.png)

Also might be nice to create a Story for this as the component is not used in full anywhere (at least not as far as I can see) so it's a bit difficult to review if the styling is correct 😄

2022-01-26 07:47 UTC, pKorsholm commented
The strange behavior is due to the old menu, if you copy the date filter menu item into product filters its not a problem

2022-01-27 18:59 UTC, olivermrbl commented on src/components/molecules/filter-dropdown/item.tsx
> +  )
It seems, that the date filter does not hold the value of the applied filter. So when you have applied a filter and re-open the date filter item, the value of the applied filter is no longer present. 

![image](https://user-images.githubusercontent.com/59018053/151425788-181ac29a-deff-4661-8e0a-e8f8bf996f9c.png)

2022-02-01 07:59 UTC, olivermrbl commented on src/components/molecules/filter-dropdown/item.tsx
> +  )
@pKorsholm Do you have an idea, why this happens?

2022-02-01 15:59 UTC, olivermrbl approved these changes
LGTM, great work! The missing persistency of the date filter will be added as part of #286 🚀

2022-02-01 16:12 UTC, merged