Fix/timeline modals
medusajs/admin pull request #320
Opened 2022-02-06 21:07 UTC by kasperkristensen

**What**

Adds modals to receive returns and fulfill items for Exchanges (swaps) and Claims.

**Things to note**
- Currently receiving an swap return will result in an 500 error being thrown on the backend due to a call to a function that does not exist. https://github.com/medusajs/medusa/blob/59761163c2f0a69dd5d1c6d73c20a80c5f08e5bd/packages/medusa/src/services/swap.js#L818
- It is currently not possible to fulfill additional items on a swap, as there is no option to add a Shipping Method to these items from the admin.
- Canceling a claim results in an error as the endpoint is defined incorrectly in medusa-react, where it is defined as /admin/orders/<claim_id>/claims//cancel

2022-02-10 14:01 UTC, olivermrbl requested changes
Very nice! Couple of comments here and there 👍

2022-02-14 08:29 UTC, kasperkristensen commented on src/components/molecules/timeline-events/claim/index.tsx
>    }
@olivermrbl Does not appear like it is working in medusa-react yet, as far as I can tell. I think we need to upgrade the version of medusa-js in medusa-react 😄

2022-02-14 14:28 UTC, olivermrbl commented
My project seems to be breaking after having merged `develop` in. The issues seem to be related to the old Toaster. Can you start it up locally @kasperkristensen ?

2022-02-14 15:50 UTC, kasperkristensen commented
@olivermrbl should be fixed now

2022-02-14 18:28 UTC, olivermrbl commented
LGTM great job @kasperkristensen! But before we merge, we should get [#1041](https://github.com/medusajs/medusa/pull/1041) merged into the core first, so we can test it out 👍

2022-02-15 13:29 UTC, srindom commented
I am not sure if this was introduced in this branch but the layered modal shows overflowing content here:

https://user-images.githubusercontent.com/7554214/154071514-2cf7648d-60e1-461c-abb5-95e315593b15.mov

2022-02-15 14:55 UTC, srindom approved these changes

2022-02-15 14:55 UTC, merged