feat: price list details
medusajs/admin pull request #510
Opened 2022-04-12 16:45 UTC by zakariaelas

### What

- adds price list detail header + prices + raw price list sections

### Notes

- "Edit price list details" coming in a different PR (depends on price list form context ticket)
- "Edit Manually" functionality coming in a different PR 
- "Import price list" functionality on hold for now
- Price row "remove product" action on hold
- Price row "Edit prices" dependent on grid editor #509 
- Price row on click dependent on #445

2022-04-13 11:23 UTC, srindom requested changes
I am unable to get this up and running. Getting this error - have tried to clean :

```
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../selectable-table' in '[..]/src/domain/pricing/details/sections/prices/prices-table'
```

2022-04-13 11:23 UTC, srindom commented on package.json
> +    "@medusajs/medusa-js": "1.1.1-dev-1649697145856",
todo: make sure that you clean up after having used `medusa-dev`

2022-04-13 13:29 UTC, zakariaelas commented
@srindom apologies I accidentally left out a file 😅 . Btw, the `SelectableTable` comes from our work on discount conditions.

2022-04-14 07:34 UTC, srindom approved these changes
LGTM!

2022-04-14 07:35 UTC, merged