fix: price list details edit manually
medusajs/admin pull request #579
Opened 2022-05-27 08:55 UTC by zakariaelas

### What

- fixes the "edit manually" feature

### How

- The `<ProductPrices />` component was using the form hook without being wrapped inside a `PriceListFormProvider`. 
- Moved logic around so that the `EditPrices` component also works as expected (while waiting for the bulk editor to come in)

2022-05-27 10:55 UTC, olivermrbl reviewed
I am seeing two different num prices for the variants.

**Edit price overrides modal**
![image](https://user-images.githubusercontent.com/59018053/170686361-e81b1464-9da3-47ac-8634-7f2c00cd45bd.png)

**Edit manually view**
![image](https://user-images.githubusercontent.com/59018053/170686440-85ca14b5-6ba0-45d8-9020-81cd8cead4de.png)

2022-05-27 11:25 UTC, olivermrbl requested changes

2022-05-27 11:25 UTC, olivermrbl commented on src/components/organisms/product-variant-tree/index.tsx
>              <span>{`${prices.length} price${
comment: Found the culprit 😄 
```suggestion
            <span>{`${filteredPrices.length} price${
```

2022-05-27 23:04 UTC, zakariaelas commented on src/components/organisms/product-variant-tree/index.tsx
>              <span>{`${prices.length} price${
haha shit nice catch 😆

2022-05-28 10:11 UTC, olivermrbl approved these changes

2022-05-28 10:11 UTC, merged