feat/add-product-subtitle
medusajs/admin pull request #632
Opened 2022-07-10 20:52 UTC by edihasaj

add product subtitle field for additional product information

2022-07-13 11:25 UTC, edihasaj commented
Yes of course, I'll do that. 👍

2022-07-22 17:41 UTC, edihasaj commented
@olivermrbl the changes are made as requested.

2022-07-26 10:12 UTC, kasperkristensen requested changes
LGTM with some minor comments that would be nice to get in before merging

2022-07-26 10:12 UTC, kasperkristensen commented on src/services/config.js
> +let medusaUrl = process.env.API_URL || "http://localhost:9000"
rm this

2022-07-26 10:12 UTC, kasperkristensen commented on src/services/request.js
> +let baseURL = process.env.API_URL || "http://localhost:9000"
rm this

2022-07-26 10:12 UTC, kasperkristensen commented on src/domain/products/product-form/sections/general.tsx
> +        </div>
```suggestion
        <div className="grid grid-cols-2 gap-x-8 mb-base">
          <Input
            id="subtitle"
            label="Subtitle"
            name="subtitle"
            placeholder="Jacket, Sunglasses..."
            ref={register()}
          />
        </div>
```

or even better

```suggestion
<div className="grid grid-rows-3 grid-cols-2 gap-x-8 gap-y-4 mb-large">
         <Input
            id="name"
            label="Name"
            name="title"
            placeholder="Jacket, Sunglasses..."
            required
            ref={register({
              required: "Name is required",
              minLength: 1,
              pattern: /(.|\s)*\S(.|\s)*/,
            })}
          />
          <Input
            tooltipContent="Handles are human friendly unique identifiers that are appropriate for URL slugs."
            label="Handle"
            name="handle"
            placeholder="bathrobe"
            prefix="/"
            ref={register()}
          />
          <Input
            id="subtitle"
            label="Subtitle"
            name="subtitle"
            placeholder="Jacket, Sunglasses..."
            ref={register()}
          />
 </div>

```

2022-08-03 11:07 UTC, kasperkristensen approved these changes

2022-08-10 11:44 UTC, merged