fix: Claim and Receive Return menus
medusajs/admin pull request #897
Opened 2023-02-13 17:20 UTC by kasperkristensen

WIP

- [x] Fix custom shipping prices not being part of requests
- [x] Fix custom refund amount not being part of requests
- [x] Refactor code, reducing the use of `useState` and `useEffect` to track payloads, and making code type safe.
- [x] Fix various errors/warnings thrown by Timeline components. 
- [ ] Improve UX around replacement claims by making their outcome more apparent.

2023-02-21 19:33 UTC, olivermrbl requested changes
I could not get far in the claims flow due to an issue with the return reasons - added a SS below. Therefore, this review is scoped to UI unrelated to RMA.

## Attempting to request a claim without a shipping address on order:
<img width="1392" alt="CleanShot 2023-02-21 at 20 08 01@2x" src="https://user-images.githubusercontent.com/59018053/220436725-086d98a5-0936-4395-a8e3-6632119277b0.png">

## Attemtping to select a return reason: 
<img width="830" alt="CleanShot 2023-02-21 at 20 10 08@2x" src="https://user-images.githubusercontent.com/59018053/220436967-505c0040-a181-4562-8ec7-3c9679cbd06a.png">

## Hover on avatar dropdown has funky outline:
<img width="211" alt="CleanShot 2023-02-21 at 20 25 24@2x" src="https://user-images.githubusercontent.com/59018053/220439744-a9b9a746-49ed-4a2a-b7fb-b43e955a8cf7.png">

2023-02-21 19:33 UTC, olivermrbl commented on src/components/molecules/timeline-events/return.tsx
> +  const args = buildReturn(event, handleCancel, openReceiveReturnMenu)
suggestion(non-blocking): Rename to something more descriptive
```suggestion
  const eventContainerArgs = buildReturn(event, handleCancel, openReceiveReturnMenu)
```

2023-02-22 08:07 UTC, kasperkristensen commented
@olivermrbl can you try again with an order without a shipping address?

2023-02-22 11:52 UTC, olivermrbl commented
@kasperkristensen Couple of additional things. A todo (bottom one) keeping me from doing anything after having requested a claim. 

**todo: I can no longer delete a requested claim:**
![CleanShot 2023-02-22 at 12 42 37](https://user-images.githubusercontent.com/59018053/220610666-7f2e3f93-60c7-42c0-ad69-9af37ea6b433.png)

**nit(non-blocking): Select has funky background on hover:**
![CleanShot 2023-02-22 at 12 44 36](https://user-images.githubusercontent.com/59018053/220610780-961168b2-23bc-4e1c-b177-ad543b90b81c.png)

todo: Cannot load order page after having requested a claim with a custom refund amount:
![CleanShot 2023-02-22 at 12 46 19](https://user-images.githubusercontent.com/59018053/220611223-23d8368f-17b2-4274-b65b-6613700f604e.png)

Above error is thrown when attempting to read `return_order.status` in the `use-build-timeline.tsx` file:
![CleanShot 2023-02-22 at 12 47 59](https://user-images.githubusercontent.com/59018053/220611623-e0069179-7a82-4af8-aa09-e55daf401dc0.png)

2023-02-22 12:03 UTC, olivermrbl commented
todo: **Refundable amount is off in "Receive return" menu:**
![CleanShot 2023-02-22 at 12 55 21](https://user-images.githubusercontent.com/59018053/220613173-78a89886-7a0a-4084-85e1-48e67f9e18a2.png)

Should we just delete the "refundable" column? Does not make much sense when you have the "Refund amount" in the summary.

praise: I absolutely love this summary:
![CleanShot 2023-02-22 at 12 58 16](https://user-images.githubusercontent.com/59018053/220613713-c67f9b85-6294-439a-aac8-c4ef676149d0.png)

2023-02-22 12:05 UTC, olivermrbl commented
nit(non-blocking): Raw JSON blob has weird pattern when collapsed:
![CleanShot 2023-02-22 at 13 04 38](https://user-images.githubusercontent.com/59018053/220615059-b00394bb-d174-4a8b-8571-95cb69ac358c.png)

2023-02-22 13:07 UTC, kasperkristensen commented
@olivermrbl I'll pinpoint the version of Tailwind which results in the weird top margin, this does show that we have a lot of cleanup to do in our styling, as this again is a result of the newer version of Tailwind not being as lenient with invalid/conflicting styles.

Refundable is not off per se, it is listing how much is refundable for the line item (`item.refundable`), so it's not correlated with the refund that is about to occur. I am good with removing it, but I am guessing that we included it in the design for some reason initially, and not sure if we would be removing some info used by admins? But I agree that it is very confusing.

I'll fix the other things you pointed out

2023-02-22 14:30 UTC, olivermrbl commented
nit: Cancel claim should be disabled when `claim.fulfillment_status === "shipped"`
![image](https://user-images.githubusercontent.com/59018053/220652355-24c75419-fd28-41b0-a0a3-293a8b829fb0.png)

2023-02-22 15:52 UTC, olivermrbl approved these changes
LGTM, absolutely fantastic work @kasperkristensen!

Quite a huge PR to get through. To be honest, I did not review every file in detail, but I tested all the flows thoroughly, and they work as expected. 

Let me know, if there's anything specific you want me to take an extra look at. Otherwise, fine to merge this in as is!

🚢 🚢 🚢

2023-02-23 10:49 UTC, pKorsholm approved these changes
LGTM

2023-02-23 10:49 UTC, merged